_extends: .github

repository:
  name: metalsmith-imagemin
  description: Metalsmith plugin to minify images.
  topics: compress,gif,imagemin,images,jpeg,jpg,metalsmith,png
  homepage: https://github.com/ahmadnassri/metalsmith-imagemin
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
