engines:
  fixme:
    enabled: true

  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript

  eslint:
    enabled: true

ratings:
  paths:
    - src/**
    - test/**
